#!/bin/bash 

print_menu(){
	echo -e "\t+------------------------------------------------------------------------+"
	echo -e "\t|                      Gestion Des Utilisateurs                          |"
	echo -e "\t+----------------------------------------------------------------------- +"
	echo -e "\t| Saisir les informations personnelles d’un salarié, taper 1.            |"
	echo -e "\t| Mettre à jour les informations personnelles d’un salarié, taper 2.     |"
	echo -e "\t| Consulter les informations personnelles d’un salarié, taper 3.         |"
	echo -e "\t| Consulter les informations personnelles de tous les salariés, taper 4. |"
	echo -e "\t| Supprimer un salarié, taper 5.                                         |"
	echo -e "\t| Quitter, taper 60                                                      |"
	echo -e "\t+------------------------------------------------------------------------+\n"
	echo -e -n "\tChoix >"
}

saisir_prenom(){
	echo -n "Prenom > "
	read prenom
	while ! [[ $prenom =~ ^[a-zA-Z]{2,}$  ]]
	do
		echo -n "Prenom > "
		read prenom
	done
}

saisir_nom(){
	echo -n "Nom > "
	read nom
	while ! [[ $nom =~ ^[a-zA-Z]{2,}$  ]]
	do
		echo -n "Nom > "
		read nom
	done
}

saisir_date(){
	echo -n "Date de Naissance (JJ/MM/YYYY) > "
	read date
	while ! [[ $date =~ ^(((0[1-9]|[12][0-9]|30)[-/]?(0[13-9]|1[012])|31[-/]?(0[13578]|1[02])|(0[1-9]|1[0-9]|2[0-8])[-/]?02)[-/]?[0-9]{4}|29[-/]?02[-/]?([0-9]{2}(([2468][048]|[02468][48])|[13579][26])|([13579][26]|[02468][048]|0[0-9]|1[0-6])00))$ ]]
	do
		echo -n "Date de Naissance (JJ/MM/YYYY) > "
  	read date
	done
}

print_menu
read choix
case $choix in
	1)
		#saisir_prenom 
		#saisir_nom
		saisir_date
		echo $date
		;;
	2)
		echo "choix 2"
		;;
	*)
		echo "Erreur"
		print_menu
		read choix
		;;
esac
