#!/bin/bash
if (( $# == 2 ));then
	if [ $(echo $1 | grep "[0-9]") ] && [ $(echo $2 | grep "[0-9]") ]; then
		  somme=$(($1+$2))
		  echo "$1 + $2 = $somme"
	else
		echo "ERROR"
		echo "Seul les caractère entre 0 - 9 sont autorisés."
	fi
else
	echo "ERROR"
	echo "Veuillez saisir le nombre d'arguments nécéssaires (2)"
fi
