#!/bin/bash
if [ $# -eq 2 ]; then
	echo "Le script est $0. Il comporte $# arguments et sa liste en est :"
	echo "$*"
	echo "Argument 1 : $1 et argument 2 : $2"
else
	echo "ERROR"
	echo "Too few arguments. Check the manual"
fi
